package com.khw.studnet_grade.entity;

import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;

import java.util.List;

@Data

public class Course {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column course.cno
     *
     * @mbggenerated Fri Dec 11 14:01:49 CST 2020
     */
    private Integer cno;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column course.cname
     *
     * @mbggenerated Fri Dec 11 14:01:49 CST 2020
     */
    private String cname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column course.tno
     *
     * @mbggenerated Fri Dec 11 14:01:49 CST 2020
     */
    private Integer tno;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column course.tname
     *
     * @mbggenerated Fri Dec 11 14:01:49 CST 2020
     */
    private String tname;
    private String score;
    private List<Score> scores;
    public Course(){}
    public Course(Integer cno, String cname, Integer tno, String tname, String score, List<Score> scores) {
        this.cno = cno;
        this.cname = cname;
        this.tno = tno;
        this.tname = tname;
        this.score = score;
        this.scores = scores;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column course.cno
     *
     * @return the value of course.cno
     *
     * @mbggenerated Fri Dec 11 14:01:49 CST 2020
     */
    public Integer getCno() {
        return cno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column course.cno
     *
     * @param cno the value for course.cno
     *
     * @mbggenerated Fri Dec 11 14:01:49 CST 2020
     */
    public void setCno(Integer cno) {
        this.cno = cno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column course.cname
     *
     * @return the value of course.cname
     *
     * @mbggenerated Fri Dec 11 14:01:49 CST 2020
     */
    public String getCname() {
        return cname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column course.cname
     *
     * @param cname the value for course.cname
     *
     * @mbggenerated Fri Dec 11 14:01:49 CST 2020
     */
    public void setCname(String cname) {
        this.cname = cname == null ? null : cname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column course.tno
     *
     * @return the value of course.tno
     *
     * @mbggenerated Fri Dec 11 14:01:49 CST 2020
     */
    public Integer getTno() {
        return tno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column course.tno
     *
     * @param tno the value for course.tno
     *
     * @mbggenerated Fri Dec 11 14:01:49 CST 2020
     */
    public void setTno(Integer tno) {
        this.tno = tno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column course.tname
     *
     * @return the value of course.tname
     *
     * @mbggenerated Fri Dec 11 14:01:49 CST 2020
     */
    public String getTname() {
        return tname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column course.tname
     *
     * @param tname the value for course.tname
     *
     * @mbggenerated Fri Dec 11 14:01:49 CST 2020
     */
    public void setTname(String tname) {
        this.tname = tname == null ? null : tname.trim();
    }
}