package com.khw.studnet_grade.entity;

public class Score {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column score.id
     *
     * @mbggenerated Sat Dec 12 09:50:48 CST 2020
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column score.sno
     *
     * @mbggenerated Sat Dec 12 09:50:48 CST 2020
     */
    private Integer sno;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column score.cno
     *
     * @mbggenerated Sat Dec 12 09:50:48 CST 2020
     */
    private Integer cno;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column score.score
     *
     * @mbggenerated Sat Dec 12 09:50:48 CST 2020
     */
    private String score;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column score.id
     *
     * @return the value of score.id
     *
     * @mbggenerated Sat Dec 12 09:50:48 CST 2020
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column score.id
     *
     * @param id the value for score.id
     *
     * @mbggenerated Sat Dec 12 09:50:48 CST 2020
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column score.sno
     *
     * @return the value of score.sno
     *
     * @mbggenerated Sat Dec 12 09:50:48 CST 2020
     */
    public Integer getSno() {
        return sno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column score.sno
     *
     * @param sno the value for score.sno
     *
     * @mbggenerated Sat Dec 12 09:50:48 CST 2020
     */
    public void setSno(Integer sno) {
        this.sno = sno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column score.cno
     *
     * @return the value of score.cno
     *
     * @mbggenerated Sat Dec 12 09:50:48 CST 2020
     */
    public Integer getCno() {
        return cno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column score.cno
     *
     * @param cno the value for score.cno
     *
     * @mbggenerated Sat Dec 12 09:50:48 CST 2020
     */
    public void setCno(Integer cno) {
        this.cno = cno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column score.score
     *
     * @return the value of score.score
     *
     * @mbggenerated Sat Dec 12 09:50:48 CST 2020
     */
    public String getScore() {
        return score;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column score.score
     *
     * @param score the value for score.score
     *
     * @mbggenerated Sat Dec 12 09:50:48 CST 2020
     */
    public void setScore(String score) {
        this.score = score == null ? null : score.trim();
    }
}