package com.khw.studnet_grade.entity;

public class Teacher {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column teacher.tno
     *
     * @mbggenerated Sat Dec 12 12:04:39 CST 2020
     */
    private Integer tno;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column teacher.tname
     *
     * @mbggenerated Sat Dec 12 12:04:39 CST 2020
     */
    private String tname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column teacher.age
     *
     * @mbggenerated Sat Dec 12 12:04:39 CST 2020
     */
    private Integer age;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column teacher.tno
     *
     * @return the value of teacher.tno
     *
     * @mbggenerated Sat Dec 12 12:04:39 CST 2020
     */
    public Integer getTno() {
        return tno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column teacher.tno
     *
     * @param tno the value for teacher.tno
     *
     * @mbggenerated Sat Dec 12 12:04:39 CST 2020
     */
    public void setTno(Integer tno) {
        this.tno = tno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column teacher.tname
     *
     * @return the value of teacher.tname
     *
     * @mbggenerated Sat Dec 12 12:04:39 CST 2020
     */
    public String getTname() {
        return tname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column teacher.tname
     *
     * @param tname the value for teacher.tname
     *
     * @mbggenerated Sat Dec 12 12:04:39 CST 2020
     */
    public void setTname(String tname) {
        this.tname = tname == null ? null : tname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column teacher.age
     *
     * @return the value of teacher.age
     *
     * @mbggenerated Sat Dec 12 12:04:39 CST 2020
     */
    public Integer getAge() {
        return age;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column teacher.age
     *
     * @param age the value for teacher.age
     *
     * @mbggenerated Sat Dec 12 12:04:39 CST 2020
     */
    public void setAge(Integer age) {
        this.age = age;
    }
}